EN = 0
AR = 1

TranslationData = {
    'Inventory Information': ['Inventory Information','معلومات المخزن'],
    'Inventory information': ['Inventory information','معلومات المخزن'],
    'Add': ['Add','إضافة'],
    'Edit': ['Edit','تعديل'],
    'Name': ['Name','الاسم'],
    'Location': ['Location','الموقع'],
    'Description': ['Description','الوصف'],
    'MoneyValue': ['MoneyValue','القيمة المالية'],
    'SerialNumber': ['SerialNumber','رقم التسلسل'],
    'Quantity': ['Quantity','الكمية'],
    'Return': ['Return','العودة'],
    'Save': ['Save','حفظ'],
    'Objects Information': ['Objects Information','معلومات العهده'],
    'Return Item': ['Return Item','ارجاع العنصر'],
    'Given State': ['Given State','حالة التسليم'],
    'Department': ['Department','القسم'],
    'Quantity': ['Quantity','الكمية'],
    'Suggested Return date': ['SuggestedReturn','الاسترجاع المتوقع'],
    'Notes': ['Notes','ملاحظات'],
    'Employee Users': ['Employee Users','اسم المستخدم للموظف'],
    'Users': ['Users', 'المستخدمين'],
    'Remove': ['Remove','حذف'],
    'Employee List': ['Employee List','فائمة الموظفين'],
    'Rank': ['Rank','التصنيف'],
    'Logout': ['Logout','تسجيل الخروج'],
    'Return Custody': ['Return Custody','ارجاع العهدة '],
    'Returned': ['Returned','مسترجع'],
    'Pay': ['Pay','دفع'],
    'Pay Loan': ['Pay Loan','دفع القرض'],
    'Damage Status': ['Damage Status','حالة الضرر'],
    'Payment Type': ['Payment Type','طريقة الدفع'],
    'Currency': ['Currency','العملة '],
    'Loan Type': ['Loan Type',' نوع القرض'],
    'Deposit Type': ['Deposit Type','نوع الايداع'],
    'Amount': ['Amount','المبلغ'],
    'Value': ['Value','القيمة'],
    'Type': ['Type','النوع'],
    'Employee Information': ['Employee Information','معلومات الموظف'],
    'Payment Information': ['Payment Information','معلومات الدفع'],
    'Asset Information': ['Asset Information','معلومات العهد'],
    'Loan Information': ['Loan Information','معلومات القرض'],
    'Employee Number': ['Employee Number','رقم الموظف'],
    'Postal Code': ['Postal Code','الرمز البريدي'],
    'Address': ['Address','العنوان'],
    'Phone': ['Phone','رقم الجوال'],
    'IBAN': ['IBAN','الايبان'],
    'Bank': ['Bank','البنك'],
    'Email': ['Email','البريد الالكتروني'],
    'MangerID': ['Manger Number','رقم المدير'],
    'Manger':['Manger Number','رقم المدير'],
    'Grade': ['Grade','الرتبة '],
    'Username':['Username','اسم المستخدم'],
    'EncPassword':['EncPassword','كلمة المرور'],
    'LoginStatus': ['LoginStatus','حالة التسجيل '],
    'AdminCheck': ['AdminCheck','تحقق من الإدارة'],
    'EmployeeID': ['EmployeeID', 'رقم تعريف الموظف'],
    'Custody App':['Custody App','نظام العهد'],
    'AdmincheckCheckbox':['AdmincheckCheckbox','خانة تحقق الإدارة'],
    'Allocation Date':['Allocation Date','تاريخ التعيين'],
    'Is Returned': ['Is Returned','تم الاسترجاع'],
    'Return Date': ['Return Date','تاريخ الاسترجاع'],
    'Suggestes Return Date':['Return Date','تاريخ  الاسترجاع المقترح'],
    'Return State': ['Return State','حالة المنتج بعد الاسترجاع'],
    'TimeStamp':['TimeStamp','التوقيت الزمني'],
    'Paid In Full': ['Paid In Full','دفع بالكامل'],
    'Is Auditor': ['Is Auditor','مدقق'],
    'Inventory Information': ['Inventory Information',''],
    'Add': ['Add','إضافة'],
    'Edit': ['Edit','تعديل'],
    'Name': ['Name','الاسم'],
    'Location': ['Location','الموقع'],
    'Description': ['Description','الوصف'],
    'MoneyValue': ['MoneyValue','القيمة المالية'],
    'SerialNumber': ['SerialNumber','رقم التسلسل'],
    'Quantity': ['Quantity','الكمية'],
    'Return': ['Return','العودة'],
    'Save': ['Save','حفظ'],
    'Objects Information': ['Objects Information','معلومات العهده'],
    'Return Item': ['Return Item','ارجاع العنصر'],
    'Given State': ['Given State','حالة التسليم'],
    'Department': ['Department','القسم'],
    'Object Name':['Object Name','اسم العهدة'],
    'Suggested Return date': ['SuggestedReturn','الاسترجاع المتوقع'],
    'Notes': ['Notes','ملاحظات'],
    'Employee Users': ['Employee Users','اسم المستخدم للموظف'],
    'Users': ['Users', 'المستخدمين'],
    'Remove': ['Remove','حذف'],
    'Employee List': ['Employee List','فائمة الموظفين'],
    'Rank': ['Rank','التصنيف'],
    'Logout': ['Logout','تسجيل الخروج'],
    'Return Custody': ['Return Custody','ارجاع العهدة '],
    'Returned': ['Returned','مسترجع'],
    'Pay': ['Pay','دفع'],
    'Pay Loan': ['Pay Loan','دفع القرض'],
    'Damage Status': ['Damage Status','حالة الضرر'],
    'Payment Type': ['Payment Type','طريقة الدفع'],
    'Failed to add payment. Payment amount exceeds the loan amount.':['Failed to add payment. Payment amount exceeds the loan amount.',"فشلت عملية إضافة الدفعة. قيمة الدفعة تتجاوز قيمة القرض"],
    'Currency': ['Currency','العملة '],
    'Loan Type': ['Loan Type',' نوع القرض'],
    'Deposit Type': ['Deposit Type','نوع الايداع'],
    'Amount': ['Amount','المبلغ'],
    'Value': ['Value','القيمة'],
    'Type': ['Type','النوع'],
    'Employee Information': ['Employee Information','معلومات الموظف'],
    'Payment Information': ['Payment Information','معلومات الدفع'],
    'Asset Information': ['Asset Information','معلومات الاصول'],
    'Loan Information': ['Loan Information','معلومات القرض'],
    'Employee Number': ['Employee Number','رقم الموظف'],
    'Postal Code': ['Postal Code','الرمز البريدي'],
    'Address': ['Address','العنوان'],
    'Is Auditor': ['Is Auditor','مدقق'],
    'Phone': ['Phone','رقم الجوال'],
    'Phone number': ['Phone number','رقم الجوال'],
    'IBAN': ['IBAN','الايبان'],
    'Bank': ['Bank','البنك'],
    'Email': ['Email','البريد الالكتروني'],
    'MangerID': ['MangerID','رقم تعريف المدير'],
    'Manager_ID': ['Manager name','اسم المدير' ],
    'Grade': ['Grade','الرتبة '],
    'Username':['Username','اسم المستخدم'],
    'LoginStatus': ['LoginStatus','حالة التسجيل '],
    'AdminCheck': ['AdminCheck','مشرف'],
    'EmployeeID': ['EmployeeID', 'رقم تعريف الموظف'],
    'Custody App':['Custody App','نظام العهد'],
    'AdmincheckCheckbox':['AdmincheckCheckbox','خانة تحقق الإدارة'],
    'TimeStamp':['TimeStamp','التوقيت الزمني'],
    'Paid In Full': ['Paid In Full','دفع بالكامل'],
    'Payment Method': ['Payment Method','طريقة الدفع'],
    'Login': ['Login','تسجيل الدخول'],
    'Password': ['Password','كلمة المرور'],
    'Arabic': ['Arabic','اللغة العربية'],
    'Password': ['Password','كلمة المرور'],
    'Serial Number': ['Serial Number','الرقم التسلسلي'],
    'Employees Records': ['Employees Records','سجلات الموظفين'],
    'Admin Check': ['Admin Check','مشرف'],
    'AddingPayment': ['AddingPayment','اضافة دفعة '],
    'Type of deposit': ['Type of deposit','نوع الوديعة '],
    'Assest Inventory': ['Assest Inventory',' مخزن العهد '],
    'Assest Allocation': ['Assest Allocation','العهد '],
    'Reset': ['Reset','اعادة ضبط '],
    'Assets': ['Assets','عهد '],
    'Loans': ['Loans','قروض '],
    'Loans Record': ['Loans Record','سجل القروض '],
    'Paymenet': ['Paymenet','الدفع '],
    'Loans Information': ['Loans Information','معلومات القرض  '],
    'Return Item': ['Return Item','اعادة العهدة '],
    'Cancel': ['Cancel','الغاء '],
    'Adding Auditor': ['Auditor Records','سجلات المدقق '],
    'Cash': ['Cash','نقد'],
    'Invalid username or password.': ['Invalid username or password.', 'اسم المستخدم أو كلمة المرور غير صالحة.'],
    'Error':['Error','خطأ'],
    'Invalid username or password.': ['Invalid username or password.', 'اسم المستخدم أو كلمة المرور غير صالحة.'],
    'Please fill in all the fields.': ['Please fill in all the fields.', 'يرجى ملء جميع الحقول.'],
    'An Deparment with the same Department Name already exists.': ['An Deparment with the same Department Name already exists.', 'يوجد قسم بنفس اسم القسم بالفعل.'],
    'phone number 10-digit number.': ['phone number 10-digit number.', 'رقم الهاتف رقم مؤلف من 10 أرقام.'],
    ' phone number 10-digit number.': ['phone number 10-digit number.', 'رقم الهاتف رقم مؤلف من 10 أرقام.'],
    'An employee with the same employee number already exists.': ['An employee with the same employee number already exists.', 'يوجد موظف بنفس رقم الموظف بالفعل.'],
    'Invalid department selected.': ['Invalid department selected.', 'تم تحديد قسم غير صالح.'],
    'Invalid Department selected.': ['Invalid Department selected.','تم تحديد قسم غير صالح.'],
    'Access Denied': ['Access Denied','منع الوصول'],
    'You do not have permission to access this feature.': ['You do not have permission to access this feature.', 'ليس لديك إذن للوصول إلى هذه الميزة.'],
    'No auditor logged in.': ['No auditor logged in.', 'لا يوجد مدقق مسجل الدخول.'],
    'Asset is already returned.': ['Asset is already returned.', 'العهدة تمت إعادتها بالفعل.'],
    'Please select an asset from the table.': ['Please select an asset from the table.', 'يرجى تحديد عهدة من الجدول.'],
    'Asset not found. Cannot return the item.': ['Asset not found. Cannot return the item.', 'لم يتم العثور على العهدة. لا يمكن إعادة العنصر.'],
    'Asset Inventory not found. Cannot return the item.': ['Asset Inventory not found. Cannot return the item.', 'لم يتم العثور على جرد الأصول. لا يمكن إعادة العنصر.'],
    'Success': ['Success', 'نجاح'],
    'No Auditor': ['No Auditor', 'لا يوجد مدقق'],
    'No Loan selected.': ['No Loan selected.', 'لم يتم تحديد قرض.'],
    'No employee selected.': ['No employee selected.', 'لم يتم تحديد موظف.'],
    'No Assest selected.': ['No Assest selected.', 'لم يتم تحديد عهدة.'],
    'No AssestInvontery selected.': ['No AssestInvontery selected.', 'لم يتم تحديد جرد الأصول.'],
    'No auditor selected.': ['No auditor selected.', 'لم يتم تحديد مدقق.'],
    'No loan selected.': ['No loan selected.', 'لم يتم تحديد قرض.'],
    'No employee selected.': ['No employee selected.', 'لم يتم تحديد موظف.'],
    'No asset allocation selected.': ['No asset allocation selected.', 'لم يتم تحديد تخصيص الأصول.'],
    'No Auditor selected.': ['No Auditor selected.', 'لم يتم تحديد مدقق.'],
    "Given State":['Given State','حالة التسليم'],
    'Return State':['Return State','حالة الارجاع'],
    'Unrecived Quantity':['Unrecived Quantity','الكمية الغير مسترجعة'],
    'Amount should be a positive number.': ['Amount should be a positive number.', 'يجب أن يكون المبلغ رقمًا موجبًا.'],
    'Failed to add payment.': ['Failed to add payment.', 'فشل في إضافة الدفعة.'],
    'An auditor with the same employee ID already exists.': ['An auditor with the same employee ID already exists.', 'يوجد مدقق بنفس رقم موظف المدقق بالفعل.'],
    'The employee ID does not exist in the employee records.': ['The employee ID does not exist in the employee records.', 'رقم موظف غير موجود في سجلات الموظفين.'],
    'Employee removed successfully.': ['Employee removed successfully.', 'تمت إزالة الموظف بنجاح.'],
    'Invalid currency, loan type, or type of deposit selected.': ['Invalid currency, loan type, or type of deposit selected.', 'تم تحديد عملة أو نوع قرض أو نوع إيداع غير صالح.'],
    'Financial loan record edited successfully.': ['Financial loan record edited successfully.', 'تم تحرير سجل القرض المالي بنجاح.'],
    'Employee edited successfully.': ['Employee edited successfully.', 'تم تحرير الموظف بنجاح.'],
    'Asset allocation edited successfully.': ['Asset allocation edited successfully.', 'تم تحرير تخصيص الأصول بنجاح.'],
    'assestInvontary record edited successfully.': ['assestInvontary record edited successfully.', 'تم تحرير سجل الجرد بنجاح.'],
    'Please fill in all the required fields.': ['Please fill in all the required fields.', 'يرجى ملء جميع الحقول المطلوبة.'],
    'Invalid department selected.': ['Invalid department selected.', 'تم تحديد قسم غير صالح.'],
    'Welcome':['Welcome','مرحبا'],
    'Payment amount exceeds the loan amount':['Payment amount exceeds the loan amount','قيمة الدفع تخطت القيمة الكلية'],
    'phone number 10-digit number':['phone number 10-digit number'],
    'Unreceived quantity is less than the returned quantity.':['Unreceived quantity is less than the returned quantity.','الكمية المسترجعة اكثر من الكمية الغير مسترجعة'],
    'Employee number':['Employee number','رقم الموظف'],
    'Please fill in all the required fields.':['Please fill in all the required fields.','يرجى ملء جميع الحقول المطلوبة.'],
    'Asset returned successfully.':['Asset returned successfully.','تم استعادة العهدة بنجاح' ],
    'Auditor added successfully.':['Auditor added successfully.','تم اضافة مدقق بنجاح' ],
    'Employee added successfully.':['Employee added successfully.','تم اضافة موظف بنجاح' ],
    'Asset added successfully.':['Asset added successfully.','تم اضافة عهدة بنجاح' ],
    'Payment added successfully.':['Payment added successfully.','تم اضافة دفعة بنجاح' ],
    'Asset Inventory added successfully.':['Asset Inventory added successfully.','تم اضافة عهدة للمخزن بنجاح' ],

    'Grade1': ['Grade1','المرتبة 1'],
    'Grade2': ['Grade2','المرتبة 2'],
    'Grade3': ['Grade3','المرتبة 3'],
    'Grade4': ['Grade4','المرتبة 4'],
    'Grade5': ['Grade5','المرتبة 5'],
    'Grade6': ['Grade6','المرتبة 6'],
    'Grade7': ['Grade7','المرتبة 7'],
    'Grade8': ['Grade8','المرتبة 8'],
    'undamaged': ['undamaged','سليم '],
    'fully_damag': ['fully_damag','ضرر كامل'],
    'low_damge': ['low_damge','ضرر طفيف'],
    'high_damge': ['high_damge','ضرر كبير'],
    'Work': ['Work','عمل'],
    'Personal': ['Personal','شخصي'],
    'Cash': ['Cash','نقدي'],
    'SaudiRiyal': ['SaudiRiyal','ريال سعودي'],
    'Dollar': ['Dollar','دولار'],
    'Euro': ['Euro','يورو'],
    'Catch_Receipt': ['Catch_Receipt','سند قبض'],
    'Bills': ['Bills','فواتير'],
    'BankTransfer': ['BankTransfer','حوالة بنكية'],
    'المرتبة 1': ['Grade1','المرتبة 1'],
    'المرتبة 2': ['Grade2','المرتبة 2'],
    'المرتبة 3': ['Grade3','المرتبة 3'],
    'المرتبة 4': ['Grade4','المرتبة 4'],
    'المرتبة 5': ['Grade5','المرتبة 5'],
    'المرتبة 6': ['Grade6','المرتبة 6'],
    'المرتبة 7': ['Grade7','المرتبة 7'],
    'المرتبة 8': ['Grade8','المرتبة 8'],
    'سليم ': ['undamaged','سليم '],
    'ضرر كامل': ['fully_damag','ضرر كامل'],
    'ضرر طفيف': ['low_damge','ضرر طفيف'],
    'ضرر كبير': ['high_damge','ضرر كبير'],
    'عمل': ['Work','عمل'],
    'شخصي': ['Personal','شخصي'],
    'نقدي': ['Cash','نقدي'],
    'ريال سعودي': ['SaudiRiyal','ريال سعودي'],
    'دولار': ['Dollar','دولار'],
    'يورو': ['Euro','يورو'],
    'سند قبض': ['Catch_Receipt','سند قبض'],
    'فواتير': ['Bills','فواتير'],
    'حوالة بنكية': ['BankTransfer','حوالة بنكية'],
    'Invalid email address.':['Invalid email address.','البريد الالكتروني خاطئ'],
    'Invalid Given status selected.': ['Invalid Given status selected.','حالة التسليم المختارة غير صحيحة'],
    'Asest is alredy Returned.': ['Asest is alredy Returned.','العهدة تم استعادتها مسبقا'],
    'Loan is Paid in full.':['Loan is Paid in full.','القرض تم تسديده بالكامل'],
    'Deletion is only available to the admin': ['Deletion is only available to the admin','خاصية الحذف للمشرفين فقط'],
    'has a Quantity of': ['has a Quantity of',' يوجد منها'],
    'The Asset Inventory record with the Object Name':['The Asset Inventory record with the Object Name','العهدة المخزنة بالاسم'],
    'Auditor edited successfully.': ['Auditor edited successfully.','تم تعديل المدقق بنجاح'],
    'Maneger number not found in system': ['Maneger number not found in system','رقم المدير غير موجود'],
    'Department added successfully.': ['Department added successfully.','تم اضافة القسم بنجاح'],
    'The employee Number does not exist in the employee records.':['The employee Number does not exist in the employee records.','رقم الموظف غير موجود'],
    'An auditor with the same employee Number already exists.':['An auditor with the same employee Number already exists.','يوجد مدقق بنفس رقم الموظف'],
    'Invalid Grade selected.':['Invalid Grade selected.','رتبة غير صحيحة'],
    'Invalid Object Name selected.':['Invalid Object Name selected.','اسم العهدة غير صحيح'],
    'By pressing this button, all recordes will be reset.':['By pressing this button, all recordes will be reset.','بالضغط على هذا الزر ستعود جميع السجلات الى حالتها الاصلية'],
    'Invalid Type Of Deposit selected.':['Invalid Type Of Deposit selected.','نوع الوديعة المختارة غير صحيحة'],
    'Invalid Currency selected.':['Invalid Currency selected.','العملة المختارة غير صحيحة'],
    'Invalid Loan Type selected.':['Invalid Loan Type selected.','نوع القرض المختار غير صحيح'],
    'Invalid Payment method selected.':['Invalid Payment method selected.','طريقة الدفع المختارة غير صحيحة'],
    'loan is Paid in full.':['loan is Paid in full.','القرض مسدد بالكامل'],
    'Invalid Return status selected.':['Invalid Return status selected.','حالة الارجاع غير صحيحة'],
    'Department Record':['Department Records','سجلات القسم'],

}


def Translateion(key: str, lang: int):
    try:
        return TranslationData[key][lang]
    except KeyError:
        # Fallback to a default translation or the key itself
        return key
    

 
