# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Rutern_Page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_inventorywindow(object):
    def setupUi(self, inventorywindow):
        inventorywindow.setObjectName("inventorywindow")
        inventorywindow.resize(314, 246)
        self.centralwidget = QtWidgets.QWidget(inventorywindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_inventory_quantity = QtWidgets.QLabel(self.centralwidget)
        self.label_inventory_quantity.setObjectName("label_inventory_quantity")
        self.gridLayout.addWidget(self.label_inventory_quantity, 0, 0, 1, 1)
        self.label_Inventory_returnstate = QtWidgets.QLabel(self.centralwidget)
        self.label_Inventory_returnstate.setObjectName("label_Inventory_returnstate")
        self.gridLayout.addWidget(self.label_Inventory_returnstate, 1, 0, 1, 1)
        self.Inventory_page_ReturnItem = QtWidgets.QPushButton(self.centralwidget)
        self.Inventory_page_ReturnItem.setObjectName("Inventory_page_ReturnItem")
        self.gridLayout.addWidget(self.Inventory_page_ReturnItem, 2, 1, 1, 1)
        self.Inventory_page_cancelbutt = QtWidgets.QPushButton(self.centralwidget)
        self.Inventory_page_cancelbutt.setObjectName("Inventory_page_cancelbutt")
        self.gridLayout.addWidget(self.Inventory_page_cancelbutt, 2, 2, 1, 1)
        self.Inventory_page_Returnstate_enum = QtWidgets.QComboBox(self.centralwidget)
        self.Inventory_page_Returnstate_enum.setEditable(True)
        self.Inventory_page_Returnstate_enum.setObjectName("Inventory_page_Returnstate_enum")
        self.gridLayout.addWidget(self.Inventory_page_Returnstate_enum, 1, 1, 1, 2)
        self.Inventory_page_quantity_spinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.Inventory_page_quantity_spinbox.setMaximum(999999999)
        self.Inventory_page_quantity_spinbox.setObjectName("Inventory_page_quantity_spinbox")
        self.gridLayout.addWidget(self.Inventory_page_quantity_spinbox, 0, 1, 1, 2)
        inventorywindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(inventorywindow)
        self.statusbar.setObjectName("statusbar")
        inventorywindow.setStatusBar(self.statusbar)

        self.retranslateUi(inventorywindow)
        QtCore.QMetaObject.connectSlotsByName(inventorywindow)
        inventorywindow.setTabOrder(self.Inventory_page_quantity_spinbox, self.Inventory_page_Returnstate_enum)
        inventorywindow.setTabOrder(self.Inventory_page_Returnstate_enum, self.Inventory_page_ReturnItem)
        inventorywindow.setTabOrder(self.Inventory_page_ReturnItem, self.Inventory_page_cancelbutt)

    def retranslateUi(self, inventorywindow):
        _translate = QtCore.QCoreApplication.translate
        inventorywindow.setWindowTitle(_translate("inventorywindow", "MainWindow"))
        self.label_inventory_quantity.setText(_translate("inventorywindow", "Quantity"))
        self.label_Inventory_returnstate.setText(_translate("inventorywindow", "Return State"))
        self.Inventory_page_ReturnItem.setText(_translate("inventorywindow", "Return Item"))
        self.Inventory_page_cancelbutt.setText(_translate("inventorywindow", "Cancel"))


class RuternPage (QtWidgets.QMainWindow, Ui_inventorywindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self = self.setupUi(self)

    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    inventorywindow = QtWidgets.QMainWindow()
    ui = Ui_inventorywindow()
    ui.setupUi(inventorywindow)
    inventorywindow.show()
    sys.exit(app.exec_())
